// vue3-ts-eslint-prettier/src/components/Greeting.vue
<template>
  <div class="greeting">
    <h2>{{ message }}</h2>
    <p>当前时间: {{ currentTime }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'

// 定义组件属性
interface Props {
  name: string
}

const props = defineProps<Props>()

// 计算属性
const message = computed(() => `你好, ${props.name}!`)

// 响应式状态
const currentTime = ref(new Date().toLocaleTimeString())

// 定时器引用
let timer: number | null = null

// 生命周期钩子 - 组件挂载后执行
onMounted(() => {
  // 每秒更新时间
  timer = window.setInterval(() => {
    currentTime.value = new Date().toLocaleTimeString()
  }, 1000)
})

// 生命周期钩子 - 组件卸载前执行
onUnmounted(() => {
  // 清除定时器
  if (timer) {
    clearInterval(timer)
  }
})
</script>

<style scoped>
.greeting {
  margin: 2rem 0;
  padding: 1rem;
  background-color: #42b883;
  color: white;
  border-radius: 4px;
}

h2 {
  margin-top: 0;
}
</style>

// react-ts-eslint-prettier/src/components/Greeting.tsx
// 引入React Hooks
import { useState, useEffect, useMemo } from 'react'

// 定义组件属性类型
interface GreetingProps {
  name: string // 问候对象名称
}

/**
 * 问候组件
 * 显示问候语和当前时间
 */
const Greeting: React.FC<GreetingProps> = ({ name }) => {
  // 状态管理 - 当前时间
  const [currentTime, setCurrentTime] = useState(new Date().toLocaleTimeString())

  // 计算属性 - 使用useMemo优化，仅当name变化时重新计算
  const message = useMemo(() => {
    return `你好，${name}！`
  }, [name])

  // 生命周期钩子 - 每秒更新时间
  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentTime(new Date().toLocaleTimeString())
    }, 1000)

    // 组件卸载时清理定时器
    return () => {
      clearInterval(timer)
    }
  }, [])

  return (
    <div className="greeting">
      <h2>{message}</h2>
      <p>当前时间: {currentTime}</p>
    </div>
  )
}

export default Greeting
